name: Build

on: [push]

jobs:
  build:
    # runs-on: ${{ matrix.operating-system }}
    runs-on: unbutu-last
    strategy:
      matrix:
        # operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.0']
    # name: PHP ${{ matrix.php-versions }} Build on ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: dom

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: php builder.php demo
